version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
